networks:
  default:

services:
  mysql:
    image:  mysql:8.2.0
    container_name: mysqldb
    hostname: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./script:/docker-entrypoint-initdb.d 
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql:
